version: "3.9"
services:
  bmi_calculator:
    build: 
      context: .
    environment: 
      PORT: 3000
    ports: 
      - '3000:3000'
    command: [sh, -c, "npm run test:unit && npm run test:integration"]